# Factory Droid 项目配置
# 文档: https://docs.factory.ai/cli/configuration/settings

# 信号捕获配置
signals:
  enabled: true
  mode: aggressive
  capture_failures: true
  auto_inject_lessons: true
  max_lesson_age_days: 30

# 代码审查配置
review:
  guidelines:
    - path: "**/*.py"
      guideline: |
        - 遵循 PEP8 风格指南
        - 必需类型注解（Python 3.10+）
        - 函数文档字符串使用 Google 风格
        - 使用 pytest 进行测试，覆盖率目标 >= 80%

    - path: "**/*.{js,ts,jsx,tsx}"
      guideline: |
        - 使用 TypeScript 严格模式
        - ESLint + Prettier 格式化
        - 组件使用函数式编程 + Hooks
        - 测试使用 Vitest/Jest

    - path: "**/*.ps1"
      guideline: |
        - 使用参数块定义参数
        - 必需注释-based 帮助文档
        - 错误处理使用 try/catch
        - Write-Host 用于用户输出，Write-Verbose 用于调试

# 性能配置
performance:
  auto_format: true
  format_on_save: true
  parallel_hooks: true

# 安全配置
security:
  block_sensitive_edits: true
  validate_commands: true
  log_hooks: true

# 日志配置
logging:
  level: info
  retention_days: 30
  max_file_size_mb: 50
